#!/bin/bash
set -e -u

# Only run, when connected to the on board WiFi
if [[ "$(iwgetid -r)" != 'WIFIonICE' ]]
then
    echo ''
    exit 0
fi

ICON=''
#ICON='🚄'
STATUS=$(curl https://portal.imice.de/api1/rs/status 2> /dev/null || true)

if [[ -z "$STATUS" ]]
then
    echo ''
else
    if [[ $(echo "$STATUS" | jq -r '.gpsStatus') == 'VALID' ]]
    then
        echo "$ICON $(echo "$STATUS" | jq -r '.speed') km/h"
    else
        echo "<span foreground=\"#a0a0a0\">$ICON</span>"
    fi
fi
