config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_i3blocks:
    dst: ~/.config/i3blocks
    src: config/i3blocks
  d_todo.actions.d:
    dst: ~/.todo.actions.d
    src: todo.actions.d
    link: link
  f_asdfrc:
    dst: ~/.asdfrc
    src: asdfrc
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_default-gems:
    dst: ~/.default-gems
    src: default-gems
  f_fonts.conf:
    dst: ~/.fonts.conf
    src: fonts.conf
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore:
    dst: ~/.gitignore
    src: gitignore
  f_lprdupconfig:
    dst: ~/.lprdupconfig
    src: lprdupconfig
  f_ranger_rc.conf:
    dst: ~/.config/ranger/rc.conf
    src: config/ranger/rc.conf
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  simon-xps13:
    dotfiles:
    - ALL
    variables:
      display_scale: 2
  simonlx:
    dotfiles:
    - ALL
    variables:
      display_scale: 1
  simon-laptop:
    dotfiles:
    - ALL
    variables:
      display_scale: 1
