#!/bin/bash

if [[ "$USER" != "root" ]]
then
    echo "Must execute as root!" >&2
    exit 1
fi

# APT-hook and regular update cron job for update notification bar
# from https://github.com/vivien/i3blocks-contrib/tree/master/apt-upgrades
ln -s $DOTFILES/custom-scripts/with-root/80i3blocks /etc/apt/apt.conf.d/
(crontab -l 2>/dev/null; echo "0 * * * * apt-get update")| crontab -


