#! /bin/bash

sudo apt-get install \
	htop \
	vim \
	git \
	meld \
	xclip \

# Install vundle and execute PluginInstall
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
