#! /bin/bash

DIR=$( cd "$( dirname "$0" )" && pwd )
export DOTFILES="$DIR/.."

# Install vundle and execute PluginInstall
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

