#! /bin/bash

DIR=$( cd "$( dirname "$0" )" && pwd )
export DOTFILES="$DIR/.."

sudo apt-get install \
	zsh \
	htop \
	vim \
	git \
	meld \
	xclip \

# Install vundle and execute PluginInstall
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Set zsh as login shell for the user
echo 'Setting /bin/zsh as your login shell. If you wish to do so enter your password. Otherwise hit Ctrl+C.'
chsh -s /bin/zsh
echo 'You need to log out and back in again so that zsh will become your default shell.'
