#!/bin/bash
set -e -u

IMAGE="$HOME/.config/background"
OUTPUT="$HOME/.cache/lock_screen.png"
LOCK_ICON="$HOME/.dotfiles/scripts/icons/lock.png"

SCREEN_SIZE='1920x1980'
PARAMS_DISPLAY_BACKGROUNDS=()
PARAMS_DISPLAY_OVERLAYS=()

# Regexes to parse screen and display sizes from xrandr
RE_SCREEN_SIZE='current ([0-9]+) x ([0-9]+)'
RE_DISPLAY_SIZE='([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)'

while read LINE
do
    if [[ $LINE =~ $RE_SCREEN_SIZE ]]
    then
        SCREEN_WIDTH="${BASH_REMATCH[1]}"
        SCREEN_HEIGHT="${BASH_REMATCH[2]}"
        SCREEN_SIZE="${SCREEN_WIDTH}x${SCREEN_HEIGHT}"
    elif [[ $LINE =~ $RE_DISPLAY_SIZE ]]
    then
        DISP_W="${BASH_REMATCH[1]}"
        DISP_H="${BASH_REMATCH[2]}"
        DISP_X="${BASH_REMATCH[3]}"
        DISP_Y="${BASH_REMATCH[4]}"

        DISP_SIZE="${DISP_W}x${DISP_H}"

        # X and Y coordinates of the display center with 'gravity center' ie. (0,0) is the center of the screen
        DCX=$(( DISP_X + (DISP_W / 2) - (SCREEN_WIDTH / 2) ))
        DCY=$(( DISP_Y + (DISP_H / 2) - (SCREEN_HEIGHT / 2) ))

        PARAMS_DISPLAY_BACKGROUNDS+=( \( "$IMAGE" -resize "$DISP_SIZE^" -gravity center -extent "$DISP_SIZE" -blur 0x5 \) -gravity NorthWest -geometry "+$DISP_X+$DISP_Y" -composite )
        PARAMS_DISPLAY_OVERLAYS+=( -annotate $(printf '%+d%+d' $DCX $(( DCY + 120 ))) 'Type password to unlock' )
        PARAMS_DISPLAY_OVERLAYS+=( "$LOCK_ICON" -gravity center -geometry $(printf '%+d%+d' $DCX $DCY) -composite )
    fi
done <<<"$(xrandr)"

convert -size "$SCREEN_SIZE" xc:none \
    "${PARAMS_DISPLAY_BACKGROUNDS[@]}" \
    -font Roboto-Thin -pointsize 32 -fill white -gravity center \
    "${PARAMS_DISPLAY_OVERLAYS[@]}" \
    "$OUTPUT"

