#!/bin/bash
# Open given workspace on other output and keep focus on current workspace
# requires jq

TARGET_WORKSPACE="$1"

INITIAL_OUTPUT=$(i3-msg -t get_workspaces | jq -r ".[] | select(.focused==true).output")
CURRENT_OUTPUT=$(i3-msg -t get_workspaces | jq -r ".[] | select(.name==\"$TARGET_WORKSPACE\").output")

i3-msg workspace "$TARGET_WORKSPACE"

if [[ "${CURRENT_OUTPUT}" == "${INITIAL_OUTPUT}" ]] ; then
  # Moving both left and up to get to other of two screens regardless of setup
  i3-msg move workspace to output left
  i3-msg move workspace to output up
fi

# Focusing both left and up to get to other of two screens regardless of setup
i3-msg focus output left
i3-msg focus output up
