#!/usr/bin/env ruby

INPUT_PATH = "#{ENV['HOME']}/Notes/Irgendwann-Vielleicht.md"
#INPUT_PATH = 'Test.md'

OUTPUT_PATH = "#{ENV['HOME']}/.cache/maybe-matrix.html"

Entry = Struct.new(
  :line,
  :section,
  :text,
  :time,
  :value,
  :status,
  keyword_init: true,
)

class SectionHierarchy
  attr_reader :titles

  def initialize(titles = [])
    @titles = titles.freeze
  end

  def next(level:, title:)
    new_titles = @titles[0...level]
    new_titles[level] = title
    self.class.new(new_titles.freeze)
  end
end

module FileParser
  def self.parse_maybe_file(data)
    current_section = SectionHierarchy.new
    data.split("\n").each_with_index.map do |line, line_number|
      line = line.rstrip

      section_match = /\A([#]+) (.*)/.match(line)
      if section_match
        section_level = section_match[1].length - 1
        section_title = section_match[2].strip
        current_section = current_section.next(level: section_level, title: section_title)
        next
      else
        next unless line.start_with?('- ')

        time_match = /t:([0-9]+)/.match(line)
        value_match = /v:([0-9]+)/.match(line)
        status_match = /s:([^ ]+)/.match(line)

          Entry.new(
          line: line_number + 1,
          section: current_section,
          text: line.strip.gsub(/\A-/, '').gsub(/[tvs]:[^ ]+/, '').strip,
          time: time_match ? Integer(time_match[1]) : nil,
          value: value_match ? Integer(value_match[1]) : nil,
          status: status_match ? status_match[1] : nil,
        )
      end
    end.compact
  end
end

module DataAggregator
  TIME_BUCKETS = [1, 2, 3, 5, 8, 13, 21, '∞']

  VALUE_VALUES = [1, 2, 3]

  def self.aggregate(entries)
    aggregated = TIME_BUCKETS.map {|bucket| [bucket, VALUE_VALUES.map {|value| [value, []] }.to_h] }.to_h
    unmatched = []
    entries.each do |entry|
      if entry.time != nil && VALUE_VALUES.include?(entry.value)
        time_bucket = TIME_BUCKETS.find {|bucket| bucket.is_a?(String) || bucket >= entry.time }
        aggregated[time_bucket][entry.value] << entry
      else
        unmatched << entry
      end
    end
    [aggregated, unmatched]
  end
end

module HTMLRenderer
  def self.stylesheet
    <<~CSS
      body {
        font-family: sans-serif;
        background-color: #f7f7fa;
        margin: 0;
      }

      ul {
        list-style: none;
        padding: 0;
        margin: 0;
      }

      main {
        margin: 8px;
      }

      main > section {
        margin-bottom: 16px;
      }

      .scrollbox {
        overflow-x: auto;
      }

      table.board {
        width: 100%;
        border-collapse: collapse;
        --grid-definition: 1px solid silver;
      }

      table.board th, table.board td {
        vertical-align: top;
      }

      table.board td {
        border: var(--grid-definition);
        width: min-content;
        width: min-intrinsic;
        padding: 16px;
      }

      table.board th {
        position: relative;
      }

      table.board th.both::after {
        content: "";
        position: absolute;
        bottom: 0;
        right: 0;
        height: 0.5em;
        width: 0.5em;
        border-right: var(--grid-definition);
        border-bottom: var(--grid-definition);
      }

      table.board th[scope=col]::after {
        content: "";
        position: absolute;
        bottom: 0;
        right: 0;
        height: 0.5em;
        border-left: var(--grid-definition);
      }

      table.board th[scope=row]::after {
        content: "";
        position: absolute;
        bottom: 0;
        right: 0;
        width: 0.5em;
        border-bottom: var(--grid-definition);
      }

      table.board th[scope=row] {
        width: 50px;
      }

      ul.board--card-list {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
        grid-gap: 16px;
      }

      ul.board--card-list > li {
        box-shadow: 0 2px 6px 0 rgba(0, 0, 0, 0.3), 0 4px 8px 0 rgba(0, 0, 0, 0.1);
        background-color: white;

        padding: 3px;
      }

      ul.board--card-list > li.on-hold {
        opacity: 0.4;
      }

      ul.card-rows > li:not(:last-child) {
        margin-bottom: 5px;
      }

      ul.card-header {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        color: silver;
        margin: 0 -2px;
      }

      ul.card-header > li {
        flex: none;
        margin: 0 2px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      ul.card-header > li:not(:first-child):not(:last-child) {
        flex-shrink: 1;
      }
    CSS
  end
  def self.render_site(table, unmatched)
    <<~HTML
      <html>
        <head>
          <title>Irgendwann Vieleicht</title>
          <style>
            #{stylesheet}
          </style>
        </head>
        <body>
          <main>
            <section>
              <div class="scrollbox">
                #{render_table(table)}
              </div>
            </section>
            <section>
              #{render_card_list(unmatched)}
            </section>
          </main>
        </body>
      </html>
    HTML
  end

  def self.render_table(table)
    <<~HTML
      <table class="board">
        <thead>
          <tr>
            <th class="both"></th>
            <th scope="col">Must Have</th>
            <th scope="col">Should Have</th>
            <th scope="col">Nice to Have</th>
          </tr>
        </thead>
        <tbody>
          #{table.map {|row| render_row(*row) }.join}
        </tbody>
      </table>
    HTML
  end

  def self.render_row(title, columns)
    <<~HTML
      <tr>
        <th scope="row">#{title}</th>
        #{columns.map {|_, items| render_cell(items) }.join}
      </tr>
    HTML
  end

  def self.render_cell(items)
    <<~HTML
      <td>
        #{render_card_list(items)}
      </td>
    HTML
  end

  def self.render_card_list(items)
    <<~HTML
      <ul class="board--card-list">
        #{items.map {|item| render_item(item) }.join}
      </ul>
    HTML
  end

  def self.render_item(item)
    section_title = item.section.titles.join(" / ")
    <<~HTML
      <li class="#{item.status}">
        <ul class="card-rows">
          <li>
            <ul class="card-header">
              <li>##{item.line}</li>
              <li title="#{section_title}">#{section_title}</li>
              <li>#{"#{item.time}h" if item.time}</li>
            </ul>
          </li>
          <li>
            #{item.text}
          </li>
        </ul>
      </li>
    HTML
  end
end


entries = FileParser.parse_maybe_file(File.read(INPUT_PATH))
aggregated, unmatched = DataAggregator.aggregate(entries)

File.open(OUTPUT_PATH, 'w') do |output|
  output.puts HTMLRenderer.render_site(aggregated, unmatched)
end
