#!/usr/bin/env ruby

INPUT_PATH = '/home/simon/Notes/Irgendwann-Vielleicht.md'
#INPUT_PATH = 'Test.md'

Entry = Struct.new(
  :line,
  :section,
  :text,
  :time,
  :value,
  keyword_init: true,
)

class SectionHierarchy
  attr_reader :titles

  def initialize(titles = [])
    @titles = titles.freeze
  end

  def next(level:, title:)
    new_titles = @titles[0...level]
    new_titles[level] = title
    self.class.new(new_titles.freeze)
  end
end

module FileParser
  def self.parse_maybe_file(data)
    current_section = SectionHierarchy.new
    data.split("\n").each_with_index.map do |line, line_number|
      line = line.strip

      section_match = /\A([#]+) (.*)/.match(line)
      if section_match
        section_level = section_match[1].length - 1
        section_title = section_match[2].strip
        current_section = current_section.next(level: section_level, title: section_title)
        next
      else
        next unless line.start_with?('- ')

        time_match = /t:([0-9]+)/.match(line)
        value_match = /v:([0-9]+)/.match(line)
        next unless time_match && value_match

        Entry.new(
          line: line_number + 1,
          section: current_section,
          text: line.strip.gsub(/\A-/, '').gsub(/[tv]:[0-9]+/, '').strip,
          time: Integer(time_match[1]),
          value: Integer(value_match[1]),
        )
      end
    end.compact
  end
end

module DataAggregator
  TIME_BUCKETS = [0, 1, 2, 3, 5, 8, 13, 21, '∞']

  VALUE_VALUES = [1, 2, 3]

  def self.aggregate(entries)
    aggregated = TIME_BUCKETS.map {|bucket| [bucket, VALUE_VALUES.map {|value| [value, []] }.to_h] }.to_h
    entries.each do |entry|
      next unless VALUE_VALUES.include?(entry.value)
      time_bucket = TIME_BUCKETS.find {|bucket| bucket.is_a?(String) || bucket >= entry.time }
      aggregated[time_bucket][entry.value] << entry
    end
    aggregated
  end
end

module HTMLRenderer
  def self.stylesheet
    <<~CSS
      body {
        font-family: sans-serif;
        background-color: #f7f7fa;
      }

      ul {
        list-style: none;
        padding: 0;
      }

      table.board {
        width: 100%;
        border-collapse: collapse;
      }

      table.board th, table.board td {
        border: 1px solid silver;
        vertical-align: top;
      }

      table.board td {
        width: min-content;
        width: min-intrinsic;
      }

      table.board th[scope=row] {
        width: 50px;
      }

      ul.board--card-list {
        margin: 0;
        padding: 4px;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      }

      ul.board--card-list > li {
        box-shadow: 0 2px 6px 0 rgba(0, 0, 0, 0.3), 0 4px 8px 0 rgba(0, 0, 0, 0.1);
        background-color: white;
        margin: 8px;

        padding: 3px;
      }

      ul.card-rows > li:not(:last-child) {
        margin-bottom: 5px;
      }

      ul.card-header {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        color: silver;
        margin: 0 -2px;
      }

      ul.card-header > li {
        flex: none;
        margin: 0 2px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      ul.card-header > li:not(:first-child):not(:last-child) {
        flex-shrink: 1;
      }
    CSS
  end
  def self.render_site(table)
    <<~HTML
      <html>
        <head>
          <title>Irgendwann Vieleicht</title>
          <style>
            #{stylesheet}
          </style>
        </head>
        <body>
          #{render_table(table)}
        </body
      </html>
    HTML
  end

  def self.render_table(table)
    <<~HTML
      <table class="board">
        <thead>
          <tr>
            <th scope="row"></th>
            <th>Richtig Cool</th>
            <th>Ganz Nett</th>
            <th>Meh</th>
          </tr>
        </thead>
        <tbody>
          #{table.map {|row| render_row(*row) }.join}
        </tbody>
      </table>
    HTML
  end

  def self.render_row(title, columns)
    <<~HTML
      <tr>
        <th scope="row">#{title}</th>
        #{columns.map {|_, items| render_cell(items) }.join}
      </tr>
    HTML
  end

  def self.render_cell(items)
    <<~HTML
      <td>
        <ul class="board--card-list">
          #{items.map {|item| render_item(item) }.join}
        </ul>
      </td>
    HTML
  end

  def self.render_item(item)
    <<~HTML
      <li>
        <ul class="card-rows">
          <li>
            <ul class="card-header">
              <li>##{item.line}</li>
              <li>#{item.section.titles.join(" / ")}</li>
              <li>#{item.time}h</li>
            </ul>
          </li>
          <li>
            #{item.text}
          </li>
        </ul>
      </li>
    HTML
  end
end


entries = FileParser.parse_maybe_file(File.read(INPUT_PATH))
pp entries
aggregated = DataAggregator.aggregate(entries)
#pp aggregated

OUTPUT_PATH = 'maybe-matrix.html'

File.open(OUTPUT_PATH, 'w') do |output|
  output.puts HTMLRenderer.render_site(aggregated)
end
