#!/usr/bin/env python3

import mido
import os

print(mido.get_input_names())

input_name = 'MPK mini 3:MPK mini 3 MIDI 1 32:0'

with mido.open_input(input_name) as port:
    for message in port:
        print(message)
        if message.type == 'control_change' and message.control == 64:
            if message.value > 63:
                print('pedal down')
                os.system('xdotool mousedown 1')
            else:
                print('pedal up')
                os.system('xdotool mouseup 1')
