#!/bin/bash
set -u

source ~/.config/dotdrop_variables.sh

PRIMARY_DESCR=$(xrandr | grep primary)

DOCK_HEIGHT=$((24 * DOTDROP_DISPLAY_SCALE))
OFFSET='+0+0'

if [[ $PRIMARY_DESCR =~ [0-9]*x[0-9]+\+([0-9]+\+[0-9]+) ]]
then
    OFFSET="${BASH_REMATCH[1]}"
fi

pkill --exact compton || true  # kill compton or ignore if not running
compton -b --shadow-exclude-reg "x${DOCK_HEIGHT}+${OFFSET}"
