#!/bin/bash
set -u

PRIMARY_DESCR=$(xrandr | grep primary)

DOCK_HEIGHT='{{@@ 24 * display_scale @@}}'
OFFSET='+0+0'

if [[ $PRIMARY_DESCR =~ [0-9]*x[0-9]+\+([0-9]+\+[0-9]+) ]]
then
    OFFSET="${BASH_REMATCH[1]}"
fi

pkill --exact compton || true  # kill compton or ignore if not running
compton -b --shadow-exclude-reg "x${DOCK_HEIGHT}+${OFFSET}"
