#!/bin/bash

SCRIPT_DIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"

XRANDR="$(xrandr)"

function duplicate_screens() {
    BASE=$1
    CLONE=$2

    if [[ $(echo "$XRANDR" | grep -A1 $BASE | grep -v $BASE) =~ ([0-9]+x[0-9]+) ]]
    then
        BASE_RESOLUTION=${BASH_REMATCH[1]}
        xrandr --fb $BASE_RESOLUTION --output $BASE --mode $BASE_RESOLUTION --scale '1x1' --output $CLONE --scale-from $BASE_RESOLUTION --same-as $BASE
    fi
}

OUTPUT_COUNT=$(echo "$XRANDR" | grep -c '\bconnected')
if [[ $OUTPUT_COUNT == 1 ]]
then
    # Get the connected output name
    CONNECTED=$(echo "$XRANDR" | grep -e '\bconnected' | cut -d ' ' -f 1)
    # Configure all outputs automatically and the connected output as primary display with it's preferred mode and no scale
    xrandr --auto --output $CONNECTED --primary $([[ $(hostname) = 'simon-xps13' ]] && echo '--mode 1920x1080' || echo '--auto') --scale '1x1'
    # Now call the post-display change hooks
    "$SCRIPT_DIR/after-screen-change"
else
    PRIMARY=$(echo "$XRANDR" | grep '\bconnected primary' | cut -d ' ' -f 1)
    OTHER=$(echo "$XRANDR" | grep -e '\bconnected [0-9]' | cut -d ' ' -f 1)
    OTHER_IS_ON=1
    if [ -z $OTHER ]
    then
        OTHER=$(echo "$XRANDR" | grep -e '\bconnected (' | cut -d ' ' -f 1)
        OTHER_IS_ON=0
    fi

    typeset -A menu
    if [[ $OTHER_IS_ON == 1 ]]
    then
        menu=(
            ["01: Place $OTHER right of $PRIMARY"]="xrandr --output $OTHER --right-of $PRIMARY"
            ["02: Place $OTHER left of $PRIMARY"]="xrandr --output $OTHER --left-of $PRIMARY"
            ["03: Place $OTHER above $PRIMARY"]="xrandr --output $OTHER --above $PRIMARY"
            ["04: Place $OTHER below $PRIMARY"]="xrandr --output $OTHER --below $PRIMARY"
            ["05: Place $OTHER same as $PRIMARY"]="xrandr --output $OTHER --same-as $PRIMARY"
            ["06: Dupliate screens at resolution of $PRIMARY"]="duplicate_screens $PRIMARY $OTHER"
            ["07: Dupliate screens at resolution of $OTHER"]="duplicate_screens $OTHER $PRIMARY"
            ["08: Use only $PRIMARY"]="xrandr --output $OTHER --off"
            ["09: Use only $OTHER"]="xrandr --output $OTHER --primary --output $PRIMARY --off"
            ["10: Make $OTHER the primary display"]="xrandr --output $OTHER --primary"
            ["11: Place $OTHER right of $PRIMARY at half scale"]="xrandr --output $OTHER --right-of $PRIMARY --scale 2x2"
            ["90: Use Preset 'Work 1080'"]="xrandr --output eDP1 --mode 1920x1080 --output DP1-3 --mode 1920x1080 --right-of eDP1 --primary"
            ["91: Use Preset 'Work 1080 Primary Small'"]="xrandr --output eDP1 --mode 1920x1080 --primary --output DP1-3 --mode 1920x1080 --right-of eDP1"
            ["95: Use Preset 'Office'"]="xrandr --output eDP1 --mode 1920x1080 --primary --output DP1 --mode 1920x1080 --above eDP1"
            ["96: Use Preset 'Office Primary Large'"]="xrandr --output eDP1 --primary --mode 1920x1080 --output DP1 --mode 1920x1080 --above eDP1"
            ["97: Use Preset 'Office 4K'"]="xrandr --output eDP1 --auto --primary --output DP1 --auto --left-of eDP1"

        )
    else
        menu=(
            ["01: Place $OTHER right of $PRIMARY"]="xrandr --output $OTHER --auto --right-of $PRIMARY"
            ["02: Place $OTHER left of $PRIMARY"]="xrandr --output $OTHER --auto --left-of $PRIMARY"
            ["03: Place $OTHER above $PRIMARY"]="xrandr --output $OTHER --auto --above $PRIMARY"
            ["04: Place $OTHER below $PRIMARY"]="xrandr --output $OTHER --auto --below $PRIMARY"
            ["05: Place $OTHER same as $PRIMARY"]="xrandr --output $OTHER --auto --same-as $PRIMARY"
            ["06: Dupliate screens at resolution of $PRIMARY"]="duplicate_screens $PRIMARY $OTHER"
            ["07: Dupliate screens at resolution of $OTHER"]="duplicate_screens $OTHER $PRIMARY"
            ["08: Use only $OTHER"]="xrandr --output $OTHER --auto --primary --output $PRIMARY --off"
            ["09: Place $OTHER right of $PRIMARY at half scale"]="xrandr --output $OTHER --auto --right-of $PRIMARY --scale 2x2"
            ["90: Use Preset 'Work 1080'"]="xrandr --output eDP1 --mode 1920x1080 --output DP1-3 --mode 1920x1080 --right-of eDP1 --primary"
            ["91: Use Preset 'Work 1080 Primary Small'"]="xrandr --output eDP1 --mode 1920x1080 --primary --output DP1-3 --mode 1920x1080 --right-of eDP1"
            ["95: Use Preset 'Office'"]="xrandr --output eDP1 --mode 1920x1080 --primary --output DP1 --mode 1920x1080 --above eDP1"
            ["96: Use Preset 'Office Primary Large'"]="xrandr --output eDP1 --primary --mode 1920x1080 --output DP1 --mode 1920x1080 --above eDP1"
            ["97: Use Preset 'Office 4K'"]="xrandr --output eDP1 --auto --primary --output DP1 --auto --left-of eDP1"
            #["91: Use Preset 'Office'"]="xrandr --output eDP1 --auto --output DP1 --auto --above eDP1 --primary"
            #["90: Use Preset 'Work 1080'"]="xrandr --output eDP1 --mode 1920x1080; sleep 1; xrandr --output DP1-3 --mode 1920x1080; sleep 1; xrandr --output DP1-3 --above eDP1 --primary"
        )
    fi


    selection=$(printf '%s\n' "${!menu[@]}" | sort | rofi -dmenu -i -p 'Display setup')
    if [[ $? -eq 0 && ! -z ${selection} ]]
    then
        # First, reset both screens to preferred mode and no scale
        xrandr --output $PRIMARY --preferred --scale 1x1 --output $OTHER --preferred --scale 1x1
        # Now apply the selected setup command
        ${menu[${selection}]}
        # Finally call the post-change hooks to re-confgure wallpapers and so on
        "$SCRIPT_DIR/after-screen-change"
    fi
fi
