#!/bin/bash
set -e -u

if [[ $(pacmd list-sinks | grep 'device.profile.name') =~ 'analog-' ]]
then
    pactl set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo
else
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
fi



