#!/bin/bash

EMOJI_FILE="$HOME/.dotfiles/scripts/emojis.txt"

# default option(s)
PASTE_COMMAND="ctrl+v"

# parse option(s)
KEY="$1"
case $KEY in
    -p|--paste-command)
        PASTE_COMMAND="$2"
        ;;
    *)
        ;;
esac

EMOJI=$(cat "$EMOJI_FILE" | rofi -dmenu -i -p 'Find emoji' | cut -d ' ' -f 1)

echo -n "$EMOJI" | xclip -i -selection clipboard
xdotool key --clearmodifiers "$PASTE_COMMAND"
