#!/bin/bash

INITIAL_WORKSPACE=$(i3-msg -t get_workspaces \
  | jq -r '.[] | select(.focused==true).name')

NON_PRIMARY_DISPLAY="$(xrandr | grep '\bconnected\b' | grep -v primary | cut -d' ' -f 1)"
xrandr --output "$NON_PRIMARY_DISPLAY" --primary

i3-msg workspace "$INITIAL_WORKSPACE"
