#!/bin/bash

kbdd_get="dbus-send --print-reply=literal --dest=ru.gentoo.KbddService /ru/gentoo/KbddService"
kbdd_send="dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService"

# Remember layout used before locking
LAYOUT=$($kbdd_get ru.gentoo.kbdd.getCurrentLayout)
LAYOUT=$(echo $LAYOUT | cut -d ' ' -f 2)

# Switch keyboard layout to german
$kbdd_send ru.gentoo.kbdd.set_layout uint32:0

# Lock screen, block till unlocked
i3lock --nofork -i ~/.cache/lock_screen.png

# Now switch keyboard layout back to previous state
$kbdd_send ru.gentoo.kbdd.set_layout uint32:$LAYOUT
