#!/bin/bash
set -u -e

FOCUSED=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)

if [[ $(xprop -id $FOCUSED _ALWAYS_BRIGHT) =~ '= 1'$ ]]
then
    xprop -id $FOCUSED -remove _ALWAYS_BRIGHT
else
    xprop -id $FOCUSED -f _ALWAYS_BRIGHT 8c -set _ALWAYS_BRIGHT 1
fi
