Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'L9'
Plugin 'vim-scripts/FuzzyFinder'
Plugin 'Valloric/YouCompleteMe'
